### ISSUE TITLE
Steps on Cloudflare Warp Beta Access doesn't work

### ISSUE THREAD

**Issue by douglasmiranda** [cloudflare/homebrew-cloudflare#2]
I can't install Warp just by typing: `brew install cloudflare-warp`

Only:
```
brew install https://raw.githubusercontent.com/cloudflare/homebrew-cloudflare/master/warp.rb
```

**Comment by c4milo** [comment]
I just run into this as well. I wanted to try it but it doesn't seem to be part of homebrew's main repo.
