### ISSUE TITLE
How to prevent brew uninstall Cloudflare http3 curl when doing brew upgrade

### ISSUE THREAD

**Issue by zoonderkins** [cloudflare/homebrew-cloudflare#35]
Hi,

I'm using command below to install curl to support http3 
```
> brew remove -f curl
> curl -O https://raw.githubusercontent.com/cloudflare/homebrew-cloudflare/master/curl.rb
```

When doing `brew upgrade`, it reinstall back to normal Mac curl.

**Comment by junhochoi** [comment]
Can you try `brew pin curl`?

**Comment by scott-prive** [comment]
@junhochoi Thanks -  can confirm `brew pin curl` works.   

Q: Can we get your suggestion added to Cloudflare's HTTP3-Curl tutorial? 
That document **_used_** to be hosted at: https://developers.cloudflare.com/http3/tutorials/curl-brew  ..

... if the docs were deleted and "never coming back", confirmation would still be very helpful (as people are looking for them). It might be the page location changed and there's no appropriate redirect so it might only seem deleted, for example. TY

**Comment by zoonderkins** [comment]
Hi I got this error on Mac M2 Mbpr, Ventura 13.4.1

```
❯ brew install --build-from-source ./curl.rb
Error: Failed to load cask: ./curl.rb
Cask 'curl' is unreadable: wrong constant name #<Class:0x0000000150476ef8>
```

**Comment by GwynethLlewelyn** [comment]
@zoonderkins have you tried with a more recent version of `homebrew-cloudflare`? Your formula is still pulling 7.81.0, while (at the time of writing) 8.2.0 is out (and soon — hopefully! — so will 8.2.1, already released for 'mainline' curl).

Maybe that fixes the compilation for you — it seems that it's just getting an old header from 7.81.0 and therefore failing.
