### ISSUE TITLE
Install guide?

### ISSUE THREAD

**Issue by elvey** [cloudflare/homebrew-cloudflare#6]
Thanks for doing the Cloudflare OpenSource thing.
I'm guessing the purpose of this repo is so folks like me can (assuming we have [Homebrew](https://brew.sh/) installed), can do something like `brew install cloudflare` to install the cloudflare CLI (Command Line Interface) tool, flarectl, on my system?  If so, or not, please add info/instructions.

**Comment by elvey** [comment]
Hmm!  
https://github.com/cloudflare/cloudflare-go/#Installation
WFM: 
`% go get github.com/cloudflare/cloudflare-go
% go get -u -v github.com/cloudflare/cloudflare-go/cmd/flarectl
`
(creates ~/go/bin/flarectl)

Now I can use the API with flarectl, e.g. instructions at https://support.cloudflare.com/hc/en-us/articles/360000841472

**Comment by elvey** [comment]
@junhochoi or @dknecht so is this the wrong repository to ask?  I'm wondering if I should ask at https://github.com/cloudflare/cloudflare-go/issues or not (wait / give up).  Anyone?  The issue, rephrased:

Summary: Instructions on how to install the cloudflare CLI (Command Line Interface) tool, flarectl from source wanted.

**Comment by junhochoi** [comment]
@elvey if you have a question on cloudflare-go, https://github.com/cloudflare/cloudflare-go/issues will be a better place to ask.

**Comment by elvey** [comment]
It looks like https://github.com/cloudflare/cloudflare-go/tree/master/cmd/flarectl has instructions for installing flarectl:

"A CLI application for interacting with a Cloudflare account."

:-)
